### ISSUE TITLE
Load Order issues

### ISSUE THREAD

**Issue by rawrfisher** [shakeyourbunny/RWMSDB#118]
Extended storage Extended depends on Extended storage to function properly.

Something in my modlist causes zen garden to break unless its loaded near the top.

Edit: I forgot to mention that the english translation for the kurin mod has to be loaded above the main mod

**Comment by shakeyourbunny** [comment]
Extended storage Extended:
Swapped categorization of both mods, should work now.

Zen Garden:
Reclassified the mod as a "biome" mod instead of "furniture", which pushes it way up. Hope this is helps.

Kurin:
This is a bit iffy because it adds so much unrelated stuff rolled into one mod and having to screw with the categorization is tricky (at least from a purist standpoint of clean and cut things ;D)

Put both in the same category (faction), hope this helps.
