### ISSUE TITLE
Mod Order Suggestion

### ISSUE THREAD

**Issue by TrippyTheO** [shakeyourbunny/RWMSDB#132]
Not sure if this is best placed in database suggestion or not, sorry if it's not. Also not sure if there's a file I should include for this or not.

TLDR: Unless Grim Reality risks overwriting something important in Rumor Has It or Rational Romance, Grim Reality would likely be better loading after those two mods.

I use a mod called Grim Reality which is responsible for making mood buffs/debuffs more realistic given the grim scenario of the game. After using RWMS it stopped working entirely correctly. Example: Executing a guilty prisoner with Grim Reality enabled gives most colonists a +1 to mood instead of the negative debuff prisoner executions usually give them. After using RWMS that stopped happening.

I moved Grim Reality beneath the only other two mods that I think might have had an effect on this: Rainbeau Flambes Rumor Has It and his Rational Romance. Grim Reality is working properly now so far as I can tell. "Justified Execution" is now a buff and other debuffs are less ridiculous though I admit I didn't take note of whether the other debuffs were functioning properly or not...I execute a lot of prisoners

**Comment by shakeyourbunny** [comment]
Improvements for mod orders are always welcome.

I also use Grim Reality and Rumour Has it, but I didn't noticed this, my prisoners (if I execute them in time) did have the +1 mood debuff though. It's maybe Rational Romance, but I use Psychology instead (the latter two are not compatible with each other).

If I already had made the rewrite of RWMS, there would be some possibility to tweak this with the loadafter directive, but for now, I moved Grim Reality down to be a patch instead of AI behaviour which is also fine I guess.

Should work now as intended (after re-running RWMS). If you have any other suggestions for load order adjustments, I'm happy to have it reported here.

Thank you!
