### ISSUE TITLE
unknown mods

### ISSUE THREAD

**Issue by h3rb4l** [shakeyourbunny/RWMSDB#147]
[rwms_unknown_mods_20190527-1531.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3223968/rwms_unknown_mods_20190527-1531.json.txt)

**Comment by shakeyourbunny** [comment]
Hello, thank you for your contribution.

Some notes:
- your are running an old version of RWMS (dunno what exactly, but the submission format is ancient)
- the next version of RWMS will introduce a new, incompatible database format to all older version and thus, older versions of RWMS will not function anymore. 
- submitting in this old database format will not give you contributor credit (for now, you got it), because of the lacking URLs for the submitted mods.
- I ran a dedupe script before processing processing the script. Dunno why, but older versions of RWMS seem to have some problems with the current database format and don't catch all known mods. 

As long as this new version is released, I'll happily accept submissions, but I'd suggest to upgrade to the most current version.

Happy playing!
