### ISSUE TITLE
Some mod categorization issues

### ISSUE THREAD

**Issue by lbmaian** [shakeyourbunny/RWMSDB#318]
"Release Animals into Wild" has a dependency on "Allow Tool". Thus it should have a category of "ui_addon".

"AnimalCollabProj Patch Pack" should load before "AnimalCollabProj Lite", as recommended in the mod description... and to avoid logged errors.

"Camera+" and "TD Enhancement Pack" have a conflict with their mouse zooming functionality. "Camera+" loading before "TD Enhancement Pack" shows no errors, while the reverse does. It's unclear what the proper fix for this would be, since "TD Enhancement Pack" does a bunch of stuff that could be categorized as both "annoyance" and "ui".

"Optimization: Meats" is another tricky one. It should be added after all animals mods, which it is. But it also should be added after any patches that could patch or remove animals, like "AnimalCollabProj Lite" above.

**Comment by lbmaian** [comment]
Was going to file a different issue for some new unknown mods, but just gonna tag it onto here:

"Vanilla Generators What Can Go Wrong?": "patch",
"AnimalFoodRestrictionInTab": "ui", // dependency on "Animal Food Restrictions"
"More Than Capable": "skill", // replacement for "Pawns are Capable"
"MBS Faux Rock (Un-Unofficial) with smoothing": "resource", // similar to "RockSmooth Walls"
"Non uno Pinata": "annoyance",
"Pumps Plus": "item", // same category as "[WD] Fast Moisture Pumps"

**Comment by shakeyourbunny** [comment]
Hi!
"Release Animals into Wild": moved to ui_addon
"AnimalCollabProj Patch Pack" got its own category for loading correctly
"Camera+/TD Enhancement Pack": moved the TD Enhancement pack to ui_addon to resolve this in a more sane way
"Optimization: Meats": should be resolved with the fix for the AnimalCollabProj Lite / Patch Set

Added your unknown mods manually except More than Capable (older ticket did submit this).
