### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by rallias** [shakeyourbunny/RWMSDB#42]
{
 "Age Morphosis Cells": "not_categorized",
 "Ancient Asian Weapons": "not_categorized",
 "Apini Playable Race": "not_categorized",
 "Don't stop the music": "not_categorized",
 "Exotic Armory": "not_categorized",
 "High Caliber": "not_categorized",
 "Industrialisation": "not_categorized",
 "Path Avoid": "not_categorized",
 "Raids Go Wrong - Toolkit Extension": "not_categorized",
 "RimFactions - Dwarven Clans": "not_categorized",
 "RimFactions - Insectoids": "not_categorized",
 "RimFactions - Synths": "not_categorized",
 "RimFactions - Wraith Legion": "not_categorized",
 "We Had a Trader?": "not_categorized",
 "Xenn Race V2": "not_categorized",
 "_contributor": "",
 "time": "Tue Apr 30 01:48:41 2019"
}

**Comment by shakeyourbunny** [comment]
Hello,

I added your mods to the database, but I'm curious if your installation is even 1.0 ;)

Can you provide the "Age Morphosis Cells" mod somewhere to download? I could not find a download location... thank you!

**Comment by v00d00y** [comment]
Since there has been no response, the 1.0 version can be found on LL (I've attached a copy as well, though I'm not the author).  Requires HugsLib, and aside from it's own functions, has a postfix on:

`RimWorld.FloatMenuMakerMap.AddHumanlikeOrders(Vector3 clickPos, Pawn pawn, List<FloatMenuOption> opts)
`

No XML patches - it adds a new building, 2 jobs, and a new research project.

[Age Morphosis CellsR1.0.zip](https://github.com/shakeyourbunny/RWMSDB/files/3142768/Age.Morphosis.CellsR1.0.zip)

**Comment by shakeyourbunny** [comment]
I already knew that it was a mod from there, but could not pinpoint it down there. Big thanks for providing it. Seems like it's just a purely medical mod, so I'll put it there.

Thank you!
