### ISSUE TITLE
For Database update. Unkown mods

### ISSUE THREAD

**Issue by Montyi** [shakeyourbunny/RWMSDB#5]
[rwms_unknown_mods_20190414-0226.txt](https://github.com/shakeyourbunny/RWMSDB/files/3076826/rwms_unknown_mods_20190414-0226.txt)

**Comment by shakeyourbunny** [comment]
I put the Children and Baby mod in the "race" category. I'd appreciate after the update if this works as intended (I hope so). The BnC is put in the "patches" category which is nearly at the end. This should work as intended by the mod author.

btw: gratulation for reporting a certain mod which I put at the very end of the load order in order to maximize compatibility.

**Comment by shakeyourbunny** [comment]
See 750c1758745a83c0d5d2958cea622fc30c650a54
